Repository ittory-project/ittory-server, pull requests merged in 2024-11, with the labels that each got.

#43 fix : 편지 박스 컬럼명 수정
  ittory-domain/src/main/java/com/ittory/domain/member/domain/LetterBox.java
Labels: bug, fix

#44 feat : 편지 시작 정보에 필드 추가
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterStartInfoResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/usecase/LetterStartInfoReadUseCase.java
Labels: feature

#45 Feature/RL1M-155
  ittory-api/src/main/java/com/ittory/api/letter/controller/CoverTypeController.java
  ittory-api/src/main/java/com/ittory/api/letter/controller/FontController.java
  ittory-api/src/main/java/com/ittory/api/letter/controller/LetterController.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterCreateRequest.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterCreateResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/usecase/LetterCreateUseCase.java
  ittory-api/src/main/java/com/ittory/api/member/controller/MemberController.java
  ittory-domain/src/main/java/com/ittory/domain/letter/service/LetterDomainService.java
Labels: feature

#46 fix : 사용자 탈퇴 사유 수정
  ittory-domain/src/main/java/com/ittory/domain/member/enums/WithdrawReason.java
Labels: fix

#54 RL1M-172 feat : Prod Cors 추가
  ittory-api/src/main/java/com/ittory/api/config/security/CorsConfig.java
Labels: feature

#55 Develop
  ittory-api/src/main/java/com/ittory/api/config/security/CorsConfig.java
Labels: feature

#56 RL1M-179 feat : LetterInfoResponse 변경
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterInfoResponse.java
Labels: feature

#58 RL1M-184 feat : 편지 상세조회 Response 변경
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterDetailResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterElementResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/usecase/LetterElementUseCase.java
  ittory-domain/src/main/java/com/ittory/domain/letter/service/ElementDomainService.java
Labels: fix

#59 Develop
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterDetailResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterElementResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterInfoResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/usecase/LetterElementUseCase.java
  ittory-domain/src/main/java/com/ittory/domain/letter/service/ElementDomainService.java
  ittory-domain/src/main/java/com/ittory/domain/member/exception/MemberErrorCode.java
  ittory-domain/src/main/java/com/ittory/domain/participant/exception/ParticipantException.java
  ittory-domain/src/main/java/com/ittory/domain/participant/service/ParticipantDomainService.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterEnterUseCase.java
Labels: feature, fix

#60 fix : 받은 편지함 로직 수정
  ittory-api/src/main/java/com/ittory/api/member/controller/MemberController.java
  ittory-domain/src/main/java/com/ittory/domain/member/repository/LetterBoxRepository.java
  ittory-domain/src/main/java/com/ittory/domain/member/service/MemberDomainService.java
Labels: fix

#61 Feature/rl1 m 189
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryCustom.java
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryImpl.java
  ittory-domain/src/main/java/com/ittory/domain/participant/service/ParticipantDomainService.java
  ittory-socket/src/main/java/com/ittory/socket/dto/ExitResponse.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterExitUseCase.java
Labels: fix

#62 Feature/rl1 m 190
  ittory-socket/src/main/java/com/ittory/socket/controller/LetterController.java
  ittory-socket/src/main/java/com/ittory/socket/controller/LetterProcessController.java
  ittory-socket/src/main/java/com/ittory/socket/dto/EndResponse.java
  ittory-socket/src/main/java/com/ittory/socket/dto/StartResponse.java
  ittory-socket/src/main/java/com/ittory/socket/enums/ProcessAction.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterEndUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterStartUseCase.java
Labels: feature

#64 RL1M-193 feat : 참여자 상태 추가
  ittory-domain/src/main/java/com/ittory/domain/participant/domain/Participant.java
  ittory-domain/src/main/java/com/ittory/domain/participant/enums/ParticipantStatus.java
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryCustom.java
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryImpl.java
  ittory-domain/src/main/java/com/ittory/domain/participant/service/ParticipantDomainService.java
  ittory-domain/src/test/java/com/ittory/domain/participant/service/ParticipantDomainServiceTest.java
  ittory-socket/src/main/java/com/ittory/socket/listener/WebSocketEventListener.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterEndUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterEnterUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterExitUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterStartUseCase.java
Labels: feature

#65 RL1M-196 feat : 커버타입 구성요소 추가
  ittory-api/src/main/java/com/ittory/api/letter/dto/CoverTypeSearchResponse.java
  ittory-domain/src/main/java/com/ittory/domain/letter/domain/CoverType.java
Labels: feature

#66 RL1M-197 feat : 편지 상세조회 타입 추가
  ittory-api/src/main/java/com/ittory/api/letter/controller/LetterController.java
  ittory-api/src/main/java/com/ittory/api/letter/dto/LetterElementResponse.java
  ittory-api/src/main/java/com/ittory/api/letter/usecase/LetterElementUseCase.java
Labels: feature

#67 Feature/rl1 m 198
  ittory-domain/src/main/java/com/ittory/domain/letter/domain/Letter.java
  ittory-domain/src/main/java/com/ittory/domain/letter/enums/LetterStatus.java
  ittory-domain/src/main/java/com/ittory/domain/letter/service/LetterDomainService.java
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryCustom.java
  ittory-domain/src/main/java/com/ittory/domain/participant/repository/impl/ParticipantRepositoryImpl.java
  ittory-domain/src/main/java/com/ittory/domain/participant/service/ParticipantDomainService.java
  ittory-socket/src/main/java/com/ittory/socket/controller/LetterProcessController.java
  ittory-socket/src/main/java/com/ittory/socket/dto/DeleteResponse.java
  ittory-socket/src/main/java/com/ittory/socket/enums/ProcessAction.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterDeleteUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterEndUseCase.java
  ittory-socket/src/main/java/com/ittory/socket/usecase/LetterStartUseCase.java
Labels: feature, fix
